### ISSUE TITLE
Getting "Unable to write to User Settings because python.analysis.extraPaths is not a registered configuration." when running "Motionbuilder: Setup Code Completion" command

### ISSUE THREAD

**Issue by carlsjoelander** [nils-soderman/vscode-motionbuilder-utils#12]
Running into _"Unable to write to User Settings because python.analysis.extraPaths is not a registered configuration."_ after the command has grabbed all the snubs. 

Tried grabbing copying over the user settings from the repo into the json file but error still occurs. 

Is probably something I'm missing (_rather new to python and vscode_) but unable to get any good leads from Googling.

**Comment by nils-soderman** [comment]
Hi, when setting up code completion, this extension assumes you have the [ms-python.vscode-pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) extension installed.

I'll look into catching this error and raising a better error message when it isn't installed.

**Comment by carlsjoelander** [comment]
Sorry for the late reply,

Installing pylance did it! An error message would be great, seems that pylance gets installed automatically when you install the Python extension so this probably rarely happens to others.
