### ISSUE TITLE
Import "pyfbsdk" could not be resolved

### ISSUE THREAD

**Issue by sonix1522** [nils-soderman/vscode-motionbuilder-utils#6]
Not that much skilled to understand why it does not works for me, so I was hoping to get maybe some help here ? :)

I got Python 3.11
Using Virtual Studio Code

When I try add anything from the MoBu utils such as `from pyfbsdk import *` yellow wavy underline show up and the `Import "pyfbsdk" could not be resolved` msg pop up when I hover over it with my cursor. 

Also having bit an issue to understand how exactly I can run the debug server ? If I can ask for help here as well. 

Thanks in advance :)
![obrazek](https://github.com/nils-soderman/vscode-motionbuilder-utils/assets/119094054/7b8c0937-e367-4fc8-b691-41bf9b6f5091)
![obrazek](https://github.com/nils-soderman/vscode-motionbuilder-utils/assets/119094054/fc670486-423e-49d0-a562-7b1093d50dea)

**Comment by sonix1522** [comment]
Ah just got older version ( 1.2.4 ) of the MoBu utils and it seems to work now. So probably some bug at latest version ?

**Comment by nils-soderman** [comment]
Hi,

In version [1.3.0](https://github.com/nils-soderman/vscode-motionbuilder-utils/releases/tag/v1.3.0) the stub files/code-completion is no longer setup automatically, instead you need to run a command to do so.

To setup code-completion in 1.3.0+, open up VS Code's command palette: <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>
Then run the command `MotionBuilder: Setup Code Completion`

I'd recommend doing this with the latest version since it comes with improved code-completion.

From the command palette you can also run the command `MotionBuilder: Attach` to start the debug server & attach VS Code to MotionBuilder. If you find yourself doing this often you can always map the command to a keyboard shortcut.

Cheers,
Nils

**Comment by sonix1522** [comment]
Thank you very much. 

I got it fully working now :) I notice that If I read the main page properly, I would get the answer there. Sorry to bother you with this.

**Comment by DarcyFan** [comment]
> Hi,
> 
> In version [1.3.0](https://github.com/nils-soderman/vscode-motionbuilder-utils/releases/tag/v1.3.0) the stub files/code-completion is no longer setup automatically, instead you need to run a command to do so.
> 
> To setup code-completion in 1.3.0+, open up VS Code's command palette: Ctrl + Shift + P Then run the command `MotionBuilder: Setup Code Completion`
> 
> I'd recommend doing this with the latest version since it comes with improved code-completion.
> 
> From the command palette you can also run the command `MotionBuilder: Attach` to start the debug server & attach VS Code to MotionBuilder. If you find yourself doing this often you can always map the command to a keyboard shortcut.
> 
> Cheers, Nils

Hi, I follow this to setup code-completion, and open up VS Code's command palette: Ctrl + Shift + P Then run the command `MotionBuilder: Setup Code Completion`, but it is failured.

![Image](https://github.com/user-attachments/assets/14419dba-c2f3-40b7-ac7a-88ff89624dec)

**Comment by DarcyFan** [comment]
> Hi,
> 
> In version [1.3.0](https://github.com/nils-soderman/vscode-motionbuilder-utils/releases/tag/v1.3.0) the stub files/code-completion is no longer setup automatically, instead you need to run a command to do so.
> 
> To setup code-completion in 1.3.0+, open up VS Code's command palette: Ctrl + Shift + P Then run the command `MotionBuilder: Setup Code Completion`
> 
> I'd recommend doing this with the latest version since it comes with improved code-completion.
> 
> From the command palette you can also run the command `MotionBuilder: Attach` to start the debug server & attach VS Code to MotionBuilder. If you find yourself doing this often you can always map the command to a keyboard shortcut.
> 
> Cheers, Nils

Hi, I follow this to setup code-completion, and open up VS Code's command palette: Ctrl + Shift + P Then run the command MotionBuilder: Setup Code Completion, but it is failured.

![Image](https://github.com/user-attachments/assets/59fbba50-0574-4f10-a4da-da039ae49ca0)

![Image](https://github.com/user-attachments/assets/444cce34-8771-4a2d-a50b-0103a48232e1)

![Image](https://github.com/user-attachments/assets/25776021-4b10-4289-9a9b-4229ca2f26b1)

Is there any solution?

Thank you!
