### ISSUE TITLE
Missing stub file

### ISSUE THREAD

**Issue by wojtekjakubo** [nils-soderman/vscode-motionbuilder-utils#9]
Umm, suddenly after updating the extension stopped working for pyfbsdk and i noticed that there's missing stub file for it.

**Comment by nils-soderman** [comment]
Ah, I moved where the extension stores it's data. And so the old stub file will indeed have been deleted with the latest update.

Try running the command `MotionBuilder: Setup Code Completion` _(Through VS Code's command palette <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>)_

**Comment by wojtekjakubo** [comment]
Yeah but it's messed up on my end i think. I did a clean install of VSCode to be sure. Apparently now VSCode stores it's data in the .vscode/extensions folder. And default location of the `MotionBuilder: Setup Code Completion` is leading to AppData/Roaming.. etc. in which there is nothing there. Still only have 3 *pyi files:
`callbackframework.pyi`
`pyfbsdk_additions.pyi`
`pythonidelib.pyi`

**Comment by nils-soderman** [comment]
Seems like I forgot to pass the `recursive` flag when creating the `%AppData%\Code\User\globalStorage\nilssoderman.mobu-utils\stubs` directory, so therefore it fails.

Will push a fix for this tonight. But in the meantime if you want to get this up and running, either manually create this folder:  `%AppData%\Code\User\globalStorage\nilssoderman.mobu-utils\stubs` or choose a custom location after running the `MotionBuilder: Setup Code Completion` command.

Thanks for reporting this!

**Comment by wojtekjakubo** [comment]
awesome, thank You! :)

yeah it's working with Your workaround :)

**Comment by nils-soderman** [comment]
This has now been fixed with [2025.0.1](https://github.com/nils-soderman/vscode-motionbuilder-utils/releases/tag/2025.0.1).
Again, thank you for reporting this issue! :)
